import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../ui/globals.css";
import { LanguageProvider } from "@/context/LanguageContext";

import FooterWraper from "@/wraper/FooterWraper";
import Navbar from "@/components/Navbar";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import '@ant-design/v5-patch-for-react-19';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BASAR Group",
  description: "Generated by create next app",
  icons: {
    icon: "/basar-group-logo.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
        <LanguageProvider>
          

         
          <Navbar/>
        
          {children}
          <FooterWraper />
          
        </LanguageProvider>
         </AntdRegistry>
      </body>
    </html>
  );
}
